spring:
  application:
    name: database-service
    version: @project.version@
  profiles:
    active: home
  webflux:
    base-path: "/home"
  flyway:
    url: ${flyway-url:jdbc:postgresql://${database.host}:${database.port}/${database.name}}
    user: ${database-user:dummyUser}
    password: ${database-password:dummyPassword}
    enabled: on

database:
  host: ${database-host:localhost}
  port: ${database-port:5432}
  name: ${database-name:dummyName}
  username: ${database-user:dummyUser}
  password: ${database-password:dummyPassword}

server:
  port: 6200

logbook:
  format:
    style: json

logging:
  level:
    org.zalando.logbook: trace
#    io.r2dbc.postgresql.PARAM: DEBUG

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 6005
management:
  server:
    port: 8005

logbook:
  format:
    style: http

---

spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: false
